
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 05 09:34:53 CST 2018
//----------------------------------------------------

package proyectocompi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Type = 5;
  public static final int EOL = 8;
  public static final int ArithmeticOperator = 6;
  public static final int Delimeter = 10;
  public static final int AssignmentOperator = 7;
  public static final int VariableName = 3;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int BooleanValue = 4;
  public static final int Number = 2;
  public static final int error = 1;
}

