
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 05 15:19:35 CST 2018
//----------------------------------------------------

package proyectocompi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 23;
  public static final int Elseif = 21;
  public static final int SubOP = 9;
  public static final int DivOP = 7;
  public static final int Then = 24;
  public static final int And = 17;
  public static final int BooleanValue = 4;
  public static final int leftParenthesis = 14;
  public static final int RelationalOperator = 19;
  public static final int rightParenthesis = 15;
  public static final int AssignmentOperator = 10;
  public static final int Type = 5;
  public static final int EOL = 11;
  public static final int Or = 18;
  public static final int Delimeter = 13;
  public static final int STRING = 12;
  public static final int AddOP = 8;
  public static final int EOF = 0;
  public static final int VariableName = 3;
  public static final int If = 20;
  public static final int error = 1;
  public static final int ThreePoints = 16;
  public static final int Endif = 22;
  public static final int MultOP = 6;
  public static final int Number = 2;
}

